title: "Accord: A sane validation library for Scala"
email: "tomer@tomergabel.com"
url: "http://wix.github.io/accord"
baseurl: "/accord"

version:
  release: 0.5
  snapshot: 0.6-SNAPSHOT

markdown: kramdown

gems:
  - jemoji